name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install root dependencies
      run: npm ci
    - name: Install functions dependencies
      run: npm ci --prefix functions
    - name: Create .env.local for build
      run: |
        echo "VITE_API_KEY=${{ secrets.VITE_API_KEY_TEST }}" >> .env.local
        echo "VITE_AUTH_DOMAIN=${{ secrets.VITE_AUTH_DOMAIN_TEST }}" >> .env.local
        echo "VITE_PROJECT_ID=${{ secrets.VITE_PROJECT_ID_TEST }}" >> .env.local
        echo "VITE_MESSAGING_SENDER_ID=${{ secrets.VITE_MESSAGING_SENDER_ID_TEST }}" >> .env.local
        echo "VITE_APP_ID=${{ secrets.VITE_APP_ID_TEST }}" >> .env.local
        echo "VITE_MEASUREMENT_ID=${{ secrets.VITE_MEASUREMENT_ID_TEST }}" >> .env.local
        echo "VITE_RECAPTCHA_SITE_KEY=${{ secrets.VITE_RECAPTCHA_SITE_KEY_TEST }}" >> .env.local
    - run: npm run build
    - name: Seed test database
      run: npm run seed
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_TEST_B64 }}
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Deploy Firestore Rules to test environment
      run: |
        npm install -g firebase-tools
        firebase deploy --only firestore:rules --project ${{ secrets.VITE_PROJECT_ID_TEST }} --token ${{ secrets.FIREBASE_TOKEN_TEST }}
    - name: Create .env for Playwright tests
      run: |
        echo "VITE_API_KEY=${{ secrets.VITE_API_KEY_TEST }}" >> .env
        echo "VITE_AUTH_DOMAIN=${{ secrets.VITE_AUTH_DOMAIN_TEST }}" >> .env
        echo "VITE_PROJECT_ID=${{ secrets.VITE_PROJECT_ID_TEST }}" >> .env
        echo "VITE_MESSAGING_SENDER_ID=${{ secrets.VITE_MESSAGING_SENDER_ID_TEST }}" >> .env
        echo "VITE_APP_ID=${{ secrets.VITE_APP_ID_TEST }}" >> .env
        echo "VITE_MEASUREMENT_ID=${{ secrets.VITE_MEASUREMENT_ID_TEST }}" >> .env
        echo "VITE_RECAPTCHA_SITE_KEY=${{ secrets.VITE_RECAPTCHA_SITE_KEY_TEST }}" >> .env
    - name: Run Playwright tests against test environment
      run: npx playwright test
      env:
        CI: true
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_TEST_B64 }}
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
